# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 10) do

  create_table "bands", :force => true do |t|
    t.column "name", :string
    t.column "url",  :string
  end

  create_table "bands_people", :id => false, :force => true do |t|
    t.column "person_id", :integer
    t.column "band_id",   :integer
  end

  add_index "bands_people", ["person_id", "band_id"], :name => "index_bands_people_on_person_id_and_band_id"
  add_index "bands_people", ["band_id"], :name => "index_bands_people_on_band_id"

  create_table "people", :force => true do |t|
    t.column "first_name", :string
    t.column "last_name",  :string
    t.column "nickname",   :string
    t.column "instrument", :string
  end

  create_table "shows", :force => true do |t|
    t.column "date",        :date
    t.column "doors",       :time
    t.column "tickets",     :string
    t.column "promoter",    :string
    t.column "venue",       :string
    t.column "town",        :string
    t.column "map_link",    :string
    t.column "description", :text
  end

  create_table "songs", :force => true do |t|
    t.column "title",       :string
    t.column "mp3",         :string
    t.column "album",       :string
    t.column "year",        :date
    t.column "lyrics",      :text
    t.column "description", :text
  end

end
